sonar.projectKey=AltaPay_api-php_90804e1e-91c4-43f6-a024-51f03ac0e4e8
sonar.projectBaseDir=src
sonar.coverage.exclusions=**
# Ignore Sonar rule: Property names should match ^[a-z][a-zA-Z0-9]*$
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S116
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.php
